# Generated by Django 5.2rc1 on 2025-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255, unique=True)),
                ("model_data", models.JSONField()),
            ],
            options={
                "db_table": "initial_models",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "manufacturer",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="type",
            field=models.IntegerField(choices=[(1, "Sedan"), (2, "Truck"), (3, "SUV")]),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["name"], name="car_name_92fd50_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["type"], name="car_type_4d6746_idx"),
        ),
        migrations.AlterModelTable(
            name="car",
            table="car",
        ),
        migrations.AddIndex(
            model_name="initialmodels",
            index=models.Index(
                fields=["model_name"], name="initial_mod_model_n_e82a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(fields=["name"], name="manufacture_name_84e14e_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(
                fields=["country"], name="manufacture_country_6ffb33_idx"
            ),
        ),
    ]
